### PR TITLE
Fix J@W (KTPA) and D,G,L,E,E# (KLAL)

### LINKED ISSUE #30: New Twy configuration at KTPA near new V2 connector
J does not intersect runway. All Victor connectors seem to be renumbered.

### PR DESCRIPTION
**Pull request by ksnifte**
Resolves #30 and #10.

**TAMPA** 
1) Disconnected Twy J from 1L.

https://prnt.sc/qncy8n

**LAKELAND**
1) Fixed the new Twy D
2) Fixed the new Twy G
3) Removed a bit of funniness on Twy E
3) Added label for Twy E2
4) Added the new flight school ramp and Twy E3

https://prnt.sc/qncyp3

**Add'l Notes:**
I did _not_ add Twy M and the new hangar at KLAL, for the sake of time and prioritizing the more breaking changes.  Ticket #34 has been added for those two things.

### CODE REVIEW

**Comment by ksnifte** [comment]
@Shaneomac456 @FriedrichKayak I didn't notice that the file was indented with spaces until after I uploaded for the PR.  Do we care about keeping spaces/tabs consistent, or is it okay to leave it as is?  I'll fix it if we do care.

**Comment by FriedrichKayak** [comment]
@ksnifte I think we want this to be spaces. For consistency with the rest of the file, but also to adhere to the VRC documentation, even if it's not strictly necessary:

> Subsequent lines in a diagram definition must have 26 spaces, followed by the latitude and longitude for the start and end points of the current line segment, followed by an optional color name or value. In other words, subsequent segment definitions are identical to the starting segment definition, except that only the starting segment contains the name of the diagram in the first 26 characters. VRC will continue reading lines and adding them to the current diagram definition until it encounters the start of a new diagram (signified by a name present in the first 26 characters) or the start of a new section.

**Comment by ksnifte** [comment]
Sounds good.  Will correct.

**Comment by ksnifte** [comment]
Closing this due to me doing dumb things in my fork.  Replaced by #40.

**Pull request closed without merging**
