### PR TITLE
ASDEX Update

### PR DESCRIPTION
**Pull request by migte**
# ASDE-X Update
This PR Includes: 

## vSTARS - ASDE-X Displays
The MIA vSTARS file now brings an updated MIA ASDE-X display which includes SRS indicators.
image
_Old Display (left), New Display (right)_

In addition, there is now a FLL ASDE-X display which includes SRS indicators.
image
_Old Display (left), New Display (right)_

## VRC - Main Sector File
The main sector file now includes region data to display the MIA ASDE-X, as well as the option to display the ramp markings and the SRS indicators. Also, color definitions were cleaned up a bit (removed unused) and categorized for ease of access.
image
_Old Display (left), New Display (right)_

In addition, the main sector file now includes region data to display the FLL ASDE-X. as well as the option to display the ramp markings and SRS indicators.
image
_Old Display (left), New Display (right)_

## VRC - ASDE-X Sector Files
There is now an individual sector file for the MIA and FLL ASDEX. This file includes everything the normal sector file would have with the exception of ASDEs for other airports. In addition, this sector file rotates the display to accurately simulate real world ASDE-X displays. This also includes the option to display the ramp markings and the SRS indicators.
image
_MIA ASDE-X (left), FLL ASDE-X (right)_

## vERAM - ASDE Displays
The MIA vERAM file now brings an updated FLL ASDE display.
image
_Old Display (left), New Display (right)_

**Note: The MIA ASDE did not receive any updated due to a lack of significant changes. At some point in the future, a way to edit the MIA ASDE wireframe will be developed (KML) and any minor changes may be made then.**

## Google Earth KML File
There are now Keyhole Markup Language files which may be edited to update the FLL ASDEX/ASDE (wireframe) and the MIA ASDEX. At some point in the future, a way to edit the MIA ASDE wireframe will be developed and any future changes may be made then.
image
_KFLL ASDEX.kml & KFLL ASDE.kml (left), KMIA ASDEX (right)_

## KML2SCT2
Included in the KML folder, there is a program to convert any ASDE-X KML files into region data for sct2. To use, simply ensure the ASDEX.kml file is within the same folder as the program, and type the file's name, including ".kml".  
image
**Note: At the time of writing this note, the program can only convert polygons, and therefore only works on ASDEX files. In a future update, the program will work for both polygons and line data (to work with a wireframe ASDE.**

### CODE REVIEW

**Comment by erikquinn** [comment]
@migte What did you remove from vSTARS in 828fa87798f250ce169519c7c531baabbe9394a3?

**Comment by erikquinn** [comment]
This should also be added to vERAM and MIA vSTARS as part of this PR.

**Comment by migte** [comment]
Woopsies, I forgot about vERAM. Sorry center peoples, I will make an updated wireframe FLL for yall.

**Comment by migte** [comment]
Great news! Google earth has been giving me year old satellite imagery. A ton of taxiways have changed. Time to fix everything :)

 For ref, fixes to change:
image

Updated/mostly Fixed:
image

**Comment by migte** [comment]
Proposed changes (within PR when ready)
Original:
image

New:
image

**Comment by migte** [comment]
image
(ASDE-X most up to date)

**Comment by migte** [comment]
vERAM version added.

Note for future changes, in the process of making any changes to the ASDE, one may consider removing the FBO labels and Terminal labels from a temporary sector file. This will help remove clutter from center controller's radars, though it will remain for other users as the information may be useful.

image

Will also consult the possibility of adding SRS indicators for the ASDE-X copies.

**Comment by migte** [comment]
To potentially fix: video map runway centerlines.

**Comment by migte** [comment]
Decided to combine the KMIA and KFLL changes into one PR.

**Comment by migte** [comment]
KFLL markings 
image

**Comment by migte** [comment]
KMIA markings
image

**Comment by migte** [comment]
PR/everything is pretty much ready to go. If I find any small things from here to the future I'll get them fixed but for the most part, I think all is ready. Though I've already reviewed everything a million times, I will run another series of QA tests of the next day or so to ensure everything can be as pretty as possible.

**Comment by migte** [comment]
The real world MIA ASDE-X displays this road that goes between 8l and 8r. tbh, I think it is kind of ugly. I'll think about putting it in.

**Pull request merged**
