### PR TITLE
Remove all training files from github (see ZMA google drive)

### LINKED ISSUE #75: Remove all TWRTrainer files from github repo
The training files are all kept on the ZMA Staff Google Drive. To prevent duplication, I would like to remove them from the githubs.

### PR DESCRIPTION
**Pull request by erikquinn**
Resolves #75.

I have verified that all the files contained here are also in the drive (plus many more of course). Therefore, they can definitely be safely removed from the github (and they'll even remain accessible through the history anyway if it came down to it).

### CODE REVIEW

**Comment by FriedrichKayak** [comment]
@erikquinn Are training scenario files the responsibility of training or facilities?

**Comment by erikquinn** [comment]
Training. If future TAs don't have the expertise to edit the files, they would potentially need some help from facility engineering, but the design of the scenarios should remain fully under the training department. My two cents.

Would definitely be nice if FE showed up with `hey, i went ahead and updated the KTPA twrtrainer airport file to show the recent taxiway changes`, but I don't see that as necessarily being their responsibility.

**Comment by ksnifte** [comment]
Before merging this, we should copy off the files from this ticket because of the Mag Dec changes: https://github.com/vZMA/ZMA/pull/72

cc: @erikquinn

**Comment by erikquinn** [comment]
@ksnifte from the issue description:

> I have verified that all the files contained here are also in the drive (plus many more of course). Therefore, they can definitely be safely removed from the github (and they'll even remain accessible through the history anyway if it came down to it).

**Comment by erikquinn** [comment]
oh. nevermind. i get it. yes. 🤦‍♂️

**Pull request merged**
